name: SuperSaiyan
author: Mitchelll, Noorquacker
version: 15
description: Turns you into a Super Saiyan!
main: main.SSJ.Main
commands:
  ssj:
    description: Turns you into a Super Saiyan!
  kaioken:
    description: Kaioken Attack.