name: Super-Saiyan-Transformations
version: '${project.version}'
main: org.apache.maven.supersaiyantransformations.SSJ
api-version: 1.17
commands:
  ssj:
    description: Turns you into a Super Saiyan!
  kaioken:
    description: Kaioken Attack.
