name: Super-Saiyan-TransformationsP
version: '${project.version}'
main: org.apache.maven.supersaiyantransformationsp.SSJ
api-version: 1.19
commands:
  ssj:
    description: Turns you into a Super Saiyan!
  kaioken:
    description: Kaioken Attack.
